export { Slider, slides } from './carousel/Carousel';
export { default as Testimonial } from './testimonial/Testimonial';
export { default as Footer } from './Footer'; 
export { default as Nav } from './Nav'; 
export { default as Events } from './Events';
export { default as Blogs } from './Blogs';
export { default as Careers } from './Careers';
export { default as Newsletters } from './Newsletters';
export { default as ContentCard } from './ContentCard';
export { default as Preview } from './Preview';